name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d

      - name: Run migrations and seed
        run: docker compose exec -T laravel-api php artisan migrate:fresh --seed

      - name: Wait for API
        run: |
          timeout 120s bash -c '
            until curl -s http://localhost:8091/users/login > /dev/null; do
              echo "⏳ Waiting for API to be ready..."
              sleep 5
            done
          '

      # Install newman và reporter HTML extra
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run API Tests with Newman
        run: |
          mkdir -p reports
          newman run api-tests/collections/toolshop.postman_collection.json \
            -e api-tests/environments/local.json \
            --reporters cli,json,htmlextra \
            --timeout-request 30000 \
            --delay-request 1000 \
            --reporter-json-export reports/newman-report.json \
            --reporter-htmlextra-export reports/newman-report.html

      - name: Upload Newman Reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/
